### PR TITLE
Clarify that waitlisted is read-only on regs

### PR DESCRIPTION
**Pull request by nronnei**
Got this bit feedback from Quattro C, and it's a good one. 

They were hoping to use the waitlist feature, but were unable to. After discussing with them, the feature doesn't behave the way they expected it to and may not use it. All the same, the docs should be changed.

### CODE REVIEW

**Comment by nronnei** [comment]
Got a bunch of other commits here cos the UI checks out from whatever branch you're already on. I don't _think_ it's a problem, but gonna ask what other folks think.

**Comment by srlsoc** [comment]
@nronnei Doc changes look good. The changes will be merged into `next` and then later merged into `master`?

**Comment by nronnei** [comment]
@srlsoc yep, that's the plan.

**Review by srlsoc — APPROVED** [review]
Approved. I'm okay with the commit history.

**Pull request merged**
